# Generated by Django 2.1.8 on 2021-05-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210429_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='introduce/%Y%m%d/'),
        ),
    ]
