# Generated by Django 2.1.8 on 2021-05-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlepost_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='avatar',
            new_name='introduce',
        ),
    ]
